In [6]:
from skimage import io, img_as_float
from skimage.transform import resize
import numpy as np
import scipy.ndimage as ndi
import matplotlib.pyplot as plt


def grayscaleFloat(img):
    img = img_as_float(img)
    return np.mean(img)

def compareGrayFloat(img1, img2):
    if (-0.05 < np.mean(img1) - np.mean(img2) < 0.05):
        return True
    return False

def getImg(imgName):
    img = io.imread(imgName)
    resize(img, (60, 60), preserve_range=True).astype('uint8')
    return img

def compareToAllButOne(name1):
    min = 100
    tmpI = -1
    baseImg = getImg(name1)
    baseImg = grayscaleFloat(baseImg)
    for i in range(0,10):
        for x in range (1,11):
            name = f'baseProjetOCR/{i}_{x}.png'
            if (name != name1):

                compImg = getImg(name)
                compImg = grayscaleFloat(compImg)

                if min > abs(np.mean(baseImg) - np.mean(compImg)): 
                    tmpI = i
                    min = abs(np.mean(baseImg) - np.mean(compImg))
    
    return tmpI

mat = np.zeros(shape=(10, 10))
for i in range(0,10):
    for x in range(1,11):
        name = f'baseProjetOCR/{i}_{x}.png'
        n = compareToAllButOne(name)
        mat [i][n]+=1

print("Percentage : " + str(np.trace(mat)))
print("Confusion matrix :\n" + str(mat))

Percentage : 24.0
Confusion matrix :
[[0. 0. 0. 0. 0. 0. 1. 1. 5. 3.]
 [0. 0. 2. 0. 2. 2. 1. 2. 1. 0.]
 [1. 3. 0. 2. 3. 0. 0. 1. 0. 0.]
 [0. 1. 2. 5. 0. 1. 0. 1. 0. 0.]
 [0. 3. 3. 0. 1. 3. 0. 0. 0. 0.]
 [0. 1. 0. 0. 4. 4. 0. 1. 0. 0.]
 [3. 1. 0. 0. 0. 0. 5. 1. 0. 0.]
 [1. 3. 1. 1. 0. 1. 0. 2. 0. 1.]
 [4. 0. 0. 0. 0. 0. 1. 0. 4. 1.]
 [1. 0. 0. 1. 1. 0. 1. 1. 2. 3.]]
